### PR TITLE
Add functionality to run program programmatically

### PR DESCRIPTION
**Pull request by BradfordMedeiros**
How do you guys feel about something like this?  I preserved the functionality of the old app so there's no breaking changes.  

This allows a user to require('wetty') and start these servers programmatic ally as modules, instead of via the command line.  Also got rid of the logging to the main app since if this is going to be run as a module, shouldn't be printing out error for no reason.    This should also be helpful for dependency management in apps that are using it.  Have some hesitancy about including this in my project in another way (adds extra complexity for how I manage dependencies basically). 

Also I saw this:
```
process.on('uncaughtException', function(e) {		
    console.error('Error: ' + e);		
});
```
Related to this?
image

In the code.  Where is it actually happening?  Maybe just error catch it in a more specific place, and we can have callbacks/shut server down etc where appropriate?

Edit: 
Found the error.  Seems like this is caused when ssh server not started.  This means that the pty.spawn can return error.  This might be described as an error in that library (depends on the pov imo because the error only gets thrown when resize is called, but depends on your view of the api),  Only thing really can do here is add functionality to have error callback, which was also added.

### CODE REVIEW

**Comment by BradfordMedeiros** [comment]
@krishnasrinivas  is this repo still being maintained?  I'm seeing lots of PRs going up for it w/o much response.  If not might make sense to officially migrate it and point to another person's repo?  This is a nice useful utility.

**Comment by butlerx** [comment]
@BradfordMedeiros if @krishnasrinivas is no longer maintaining this repo ive been maintaining a fork at https://github.com/butlerx/wetty with a few changes to make it better for users

**Comment by krishnasrinivas** [comment]
@butlerx can I add you to the collaborators list of this repo? I was thinking of re-implemeting wetty in Go as there are too many issues w.r.t node/pty.js Go based static binary will be simple to deploy.

**Comment by butlerx** [comment]
@krishnasrinivas sure. I think the idea of using go is very good and would be willing to help.

**Comment by krishnasrinivas** [comment]
@butlerx I have added you to collaborators of wetty. You are free to make decisions on this project.

**Comment by butlerx** [comment]
@krishnasrinivas could we maybe email about what youre feelings on the repo are

**Comment by butlerx** [comment]
as of version 1 wetty cn be imported to another applications

**Pull request closed without merging**
