### PR TITLE
Add listen host and systemd unit file

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by binford2k** [comment]
@krishnasrinivas Are you going to add the systemd file?

**Comment by krishnasrinivas** [comment]
I have cherrypicked this commit and pushed it:

https://github.com/inducer/wetty/commit/1037814b0117d33754a0f24a7c340659bd18003d

**Comment by butlerx** [comment]
could you rebase of master

**Comment by butlerx** [comment]
covered by #155

**Pull request closed without merging**
