### PR TITLE
make it possible to define the target ssh host per url;

### PR DESCRIPTION
**Pull request by trusch**
Hello, 

I just added the possibility to select the target ssh host per url.

The URL can no be like this: http://localhost:3000/wetty/ssh/root/my-workstation

The old URL form (http://localhost:3000/wetty/ssh/root) is unaffected and is still usable.

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
Users might find this risky because anyone can use wetty as a `bouncer` to access unauthorized machines without leaving traces.

**Comment by jarrettgilliam** [comment]
I agree. I don't want unauthenticated users accessing machines on my local network.

**Comment by merlijn-sebrechts** [comment]
This is indeed risky to enable by default. Would it be a good idea to enable this using some kind of whitelist? 

The whitelist would be supplied using an environment variable or a commandline option. The Wetty instance can only connect to whitelisted servers. Localhost would be whitelisted by default. What do you think?

**Comment by trusch** [comment]
This sound reasonable. I'll try to hack it, once my newborn is fallen asleep ;)

**Comment by jarrettgilliam** [comment]
I might be alone in this, but I think this is beyond the scope of what Wetty is intended to do. I see Wetty as a way to extend a headless Linux login screen to any computer with a web browser. I don't see it as a fully fledged ssh client. I think the only reason it uses ssh is to let non-privileged users run the service. Anyone who wants this kind of functionality should look to the [Secure Shell Chrome App](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?hl=en) where SSH is done on the client side. With a little research it could probably even be served by your favorite web server instead of a packaged chrome app. Anyway, this is just my two cents. What do you think @krishnasrinivas?

**Comment by trusch** [comment]
I use wetty in a application where we manage multiple devices connected to a cloud service. The purpuse of the application is to monitor and organize these devices. I searched for a convenient way to add a "connect with ssh"-button to each of them.

It is absolutely clear that wetty is not a "fully fledged ssh client" but I think that this feature would be usefull for many people.

With the whitelist option defaulting to localhost I don't see any problems.

The whitelist implementation I added accepts a comma separated list of the form "^.*@localhost$,^foo@machine-1$" which would allow to connect as any user to localhost and as user foo to the host machine-1. The use of regexes might look over-engeneered, but it allows fine grained control.

**Comment by merlijn-sebrechts** [comment]
Thanks Trusch! I have the same use-case, so I'm really interested in
getting this patch merged.

2016-02-11 18:49 GMT+01:00 trusch notifications@github.com:

**Comment by mdavidlawson** [comment]
Same use case here... is there somewhere where we can vote on this PR?

**Comment by butlerx** [comment]
this functionality was added in v1

**Pull request closed without merging**
