### PR TITLE
Add a reconnect button on logout

### PR DESCRIPTION
**Pull request by binford2k**
Prior to this, the only way to return to a session after logging out or
login timeout was to manually reload the page. This gives you a nice
button to do it for you.

Ping @joshsamuelson

### CODE REVIEW

**Comment by binford2k** [comment]
@krishnasrinivas can this get a review & merge?

**Comment by krishnasrinivas** [comment]
@binford2k I am not able to see the input button after logout. Checked on Chrome/FF. Is it working fine for you?

**Comment by krishnasrinivas** [comment]
better thing would be to do this:

``` js
+++ b/app.js
@@ -101,35 +101,38 @@ io.on('connection', function(socket){
         sshuser = globalsshuser + '@';
     }

-    var term;
-    if (process.getuid() == 0) {
-        term = pty.spawn('/bin/login', [], {
-            name: 'xterm-256color',
-            cols: 80,
-            rows: 30
-        });
-    } else {
-        term = pty.spawn('ssh', [sshuser + sshhost, '-p', sshport, '-o', 'PreferredAuthentications=' + sshauth], {
-            name: 'xterm-256color',
-            cols: 80,
-            rows: 30
-        });
+    var newTerm = function() {
+      var term;
+      if (process.getuid() == 0) {
+          term = pty.spawn('/bin/login', [], {
+              name: 'xterm-256color',
+              cols: 80,
+              rows: 30
+          });
+      } else {
+          term = pty.spawn('ssh', [sshuser + sshhost, '-p', sshport, '-o', 'PreferredAuthentications=' + sshauth], {
+              name: 'xterm-256color',
+              cols: 80,
+              rows: 30
+          });
+      }
+      console.log((new Date()) + " PID=" + term.pid + " STARTED on behalf of user=" + sshuser)
+      term.on('data', function(data) {
+          socket.emit('output', data);
+      });
+      term.on('exit', function(code) {
+          console.log((new Date()) + " PID=" + term.pid + " ENDED");
+          newTerm()
+      });
+      socket.on('resize', function(data) {
+          term.resize(data.col, data.row);
+      });
+      socket.on('input', function(data) {
+          term.write(data);
+      });
+      socket.on('disconnect', function() {
+          term.end();
+      });
     }
-    console.log((new Date()) + " PID=" + term.pid + " STARTED on behalf of user=" + sshuser)
-    term.on('data', function(data) {
-        socket.emit('output', data);
-    });
-    term.on('exit', function(code) {
-        console.log((new Date()) + " PID=" + term.pid + " ENDED");
-        socket.emit('logout');
-    });
-    socket.on('resize', function(data) {
-        term.resize(data.col, data.row);
-    });
-    socket.on('input', function(data) {
-        term.write(data);
-    });
-    socket.on('disconnect', function() {
-        term.end();
-    });
+    newTerm()
 })
diff --git a/public/index.html b/public/index.html
```

**Comment by binford2k** [comment]
@krishnasrinivas fixed the visibility issue. I'd forgotten a css property :-/

The diff you posted is interesting, but it doesn't seem to fit in scope of this change.

**Comment by butlerx** [comment]
merged manually

**Pull request closed without merging**
