### PR TITLE
Hide scrollbar

### PR DESCRIPTION
**Pull request by gsf**
I really prefer my terms without scrollbars. I'd rather this just be the default, but also understand if it gets into a bigger discussion around setting preferences.

### CODE REVIEW

**Comment by krishnasrinivas** [comment]
I think we can leave the default as is if that's what most people prefer. gnome-terminal and other terminals have scroll bar by default too.

**Comment by gsf** [comment]
Okay. Any thoughts on how to make this configurable?

**Comment by krishnasrinivas** [comment]
The way you do in the PR seems the only good way to do it. adding a UI config will be an overkill unless we want many other things to be customizable

**Comment by krishnasrinivas** [comment]
Closing this.

**Pull request closed without merging**
