### PR TITLE
Added FAQ to README.md

### PR DESCRIPTION
**Pull request by merlijn-sebrechts**

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
So, I got someone to test it out and he can use it on IE11 without the patch. Although it might be good to keep this in the FAQ for a while just to make sure.

**Comment by jarrettgilliam** [comment]
That's looking better. If we're going to make a list of supported browsers though, we should probably test all the major ones. Some glaring omissions I see are Safari and Opera. We might even test some older versions of IE. I'm out of town right now but I could probably help with this Saturday or Sunday. Also I'm not sure the link to issue #45 is necessary.

P.S. Thanks for contributing!

**Comment by jarrettgilliam** [comment]
Wetty works with Safari and Opera just fine. I couldn't get it to work with IE 10 or below though.

**Comment by merlijn-sebrechts** [comment]
Are there any changes I need to make before this can be merged?

**Comment by butlerx** [comment]
merged manually

**Pull request closed without merging**
